FE-353 featured workspace tests
broadinstitute/terra-featured-workspace-tests pull request #8
Opened 2024-11-20 17:01 UTC by kilonzi

2025-02-11 18:00 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
> +            report_url: "https://storage.googleapis.com/terra-featured-workspace-tests-reports/fw_reports/${{env.CURRENT_DATE}}/"
This is not getting the current date
https://broadinstitute.slack.com/archives/CN5K96NMV/p1738859701474299

2025-02-11 18:04 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
> +          REPORT_NAME="master_report_batch_1${CURRENT_DATE}.html"
for each of these you probably want to put a _ after the batch number.
You're getting report names like "terra-featured-workspace-tests-reports/fw_reports/master_report_batch_12025-02-05-00-05-40.html" right now - which makes sense if you think about or look at the code, but is confusing at first glance - looks like the batch # is part of the timestamp

2025-02-11 18:44 UTC, kilonzi commented on .github/workflows/run-terra-featured-workspace-tests.yaml
> +  FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true
Yes, still needed. We still have same warning on Github Runners. We can remove it later

2025-02-11 18:48 UTC, kilonzi commented on featured_workspaces_test.py
> +            cleanup_workspaces(args.clone_project, age_days=200, verbose=args.verbose)
Nice catch, I will use 30 days

2025-02-11 18:50 UTC, kilonzi commented on .github/workflows/run-terra-featured-workspace-tests.yaml
> +            report_url: "https://storage.googleapis.com/terra-featured-workspace-tests-reports/fw_reports/${{env.CURRENT_DATE}}/"
Yes, that should now be the folder, with all the batches

2025-02-11 19:00 UTC, kilonzi commented on .github/workflows/run-terra-featured-workspace-tests.yaml
> +          REPORT_NAME="master_report_batch_1${CURRENT_DATE}.html"
yes...that needs to be changed

2025-02-12 01:50 UTC, kilonzi commented on README.md
Yes, docker will work.

2025-02-13 17:57 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
> +    if: ${{ github.event.inputs.mute_notifications != 'true' }}
in production, IE when you are not testing your changes, should this be "=true" rather than "!=true"?  - basically, don't we want to notify when this is running "for real"?

2025-02-13 18:00 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
I'm not sure what changed, but the latest run "completed" after 2 minutes with a "warning" which is actually an error:
https://github.com/broadinstitute/terra-featured-workspace-tests/actions/runs/13313913925/job/37183102489#step:8:36

2025-02-13 18:54 UTC, bahill requested changes

2025-02-13 18:54 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
> +          REPORT_NAME="master_report_batch_2_${CURRENT_DATE}.html"
This should be batch 3
It's now reporting out with the same name as real batch 2 and I think running into some race conditions with which one actually gets written to the bucket.
https://console.cloud.google.com/storage/browser/terra-featured-workspace-tests-reports/fw_reports;tab=objects?inv=1&invt=AbpeyQ&prefix=master_report_batch_2_2025-02-13&forceOnObjectsSortingFiltering=false&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22master_report_batch_2_2025-02-13_5C_22_22%257D%255D%22))

2025-02-13 18:54 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
> +          REPORT_NAME="master_report_batch_2_${CURRENT_DATE}.html"
The report name needs to match the batch # (4)

2025-02-13 18:54 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
Additionally, it seems like only a total of 4 tests were run between batches 2 & 3 
Batch 1 failed with the error above and Batch 4 didn't run anything.
Shouldn't there be 64 workspaces tested?

2025-02-13 18:54 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
It would be great if the links in the actions logs had clickable links.
Currently the folder name is derived from the project_id in the env and it seems GHA is treating that as sensitive, so we're getting URLs like:
https://storage.googleapis.com/terra-featured-workspace-***s-reports/fw_reports/master_report_batch_2_2025-02-13-17-51-21.html

Instead of https://storage.googleapis.com/terra-featured-workspace-tests-reports/fw_reports/master_report_batch_2_2025-02-13-17-51-21.html

2025-02-13 18:54 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
I'm also not sure why the individual reports are not present after this latest run
https://console.cloud.google.com/storage/browser/terra-featured-workspace-tests-reports/fw_reports;tab=objects?inv=1&invt=AbpeyQ&prefix=2025&forceOnObjectsSortingFiltering=false&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%257B_22k_22_3A_22_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_222025_5C_22_22%257D%255D%22))

2025-02-13 18:54 UTC, bahill commented on README.md
> +1. Tests are divided in 4 batches, there exists this parameter in code `batch_size = 18` that needs to be changed if number of featured workspaces.
I think this sentence is missing its end:
"if the number of featured workspaces **increases**"

2025-02-13 18:54 UTC, bahill commented on README.md
> +2. The tests run periodically every 14 days, but you can dispatch manually through Workflow Dispatcher
It would be great to be explicit here that they are running automatically via GHA. We should all know now that we are using actions and not Jenkins, but who knows what happens in a year or two.

2025-02-13 18:54 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
aha https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions#accessing-your-secrets

So, maybe you can set that as a variable for the action, rather than relying on the value from secrets?

2025-02-13 19:10 UTC, kilonzi commented on .github/workflows/run-terra-featured-workspace-tests.yaml
I see what you did. For manual testing, you have to set troubleshooting to **_false_** and mute notifications to _**false**_. This essentially runs the entire suite of 64 workspaces and 510 submissions. That ANVIL workspace have the requestor pays set on, so they will fail on clone.

2025-02-13 19:15 UTC, kilonzi commented on .github/workflows/run-terra-featured-workspace-tests.yaml
so Github will mask any words with 'test', 'password' e.t.c even if in the variable. The bucket name is actually a non-secret variable.

2025-02-25 22:34 UTC, bahill requested changes

2025-02-25 22:34 UTC, bahill commented on README.md
> +1. Tests are divided in 4 batches, there exists this parameter in code `batch_size = 18` that needs to be changed if number of featured workspaces.
This can be ignored, but it's still missing a word.

2025-02-25 22:34 UTC, bahill commented on README.md
> +2. The tests run periodically every 14 days, but you can dispatch manually through Workflow Dispatcher
Another one you can ignore, but it would be nice to be more explicit about how they are running.

2025-02-25 22:34 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
> +            report_url: "https://storage.googleapis.com/terra-featured-workspace-tests-reports/fw_reports/"
Looks like the report urls are being generated correctly:
https://storage.googleapis.com/terra-featured-workspace-***s-reports/fw_reports/_2025-02-15-00-22-43/batch_1/Trinity__2025-02-15-00-22-43.html - and you can just type in test for the *** bit - might be nice to document that.

But the URL in the Slack message isn't valid because the bucket itself, which is what this is pointing to, is not public, while the individual folder objects are.

<Error>
<Code>AccessDenied</Code>
<Message>Access denied.</Message>
<Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object. Permission 'storage.objects.get' denied on resource (or it may not exist).</Details>
</Error>

https://cloud.google.com/storage/docs/request-endpoints

2025-02-25 22:34 UTC, bahill commented on .github/workflows/run-terra-featured-workspace-tests.yaml
> +            report_url: "https://storage.googleapis.com/terra-featured-workspace-tests-reports/fw_reports/"
Also - couldn't we point to the master report for each batch instead? 1 slack per batch?
And what are the COST reports?

2025-03-04 15:44 UTC, bahill commented on featured_workspaces_test.py
Line 36:
gcs_path_imgs = gcs_path.replace('gs://', 'https://storage.googleapis.com/').replace('fw_reports/', 'imgs/')

Is incorrect - this is why the img isn't displaying in the reports. The images are stored in a top level imgs dir - not the timestamped dir.

gcs_path_imgs = gcs_path.replace('gs://', 'https://storage.googleapis.com/').replace('fw_reports/', 'imgs/')

You could use regex to fix it (you'd have to import re)
gcs_path_imgs = re.sub(r'fw_reports/.*', 'imgs/', gcs_path.replace('gs://', 'https://storage.googleapis.com/'))

BUT this is not a blocker!

![Screenshot 2025-03-04 at 10 29 23 AM](https://github.com/user-attachments/assets/36d72a88-8535-4ef5-8c1d-a3e206e5f74c)

2025-03-04 15:44 UTC, bahill approved these changes

2025-03-17 17:41 UTC, merged